[package]
name = "shared_types"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
sqlx = { version = "0.7.1", features = ["sqlite", "runtime-tokio-rustls"] }
