[database]
url = "sqlite:soldr.db?mode=rwc"

[proxy]
listen = "0.0.0.0:3000"

[management]
listen = "0.0.0.0:3443"
secret = "a secret with minimum length of 32 characters"

[tls]
enable = false
cert_path = "certs/localhost.crt"
key_path = "certs/localhost.key"

