-- up
DO
$$
BEGIN
   IF NOT EXISTS (
      SELECT
      FROM   pg_catalog.pg_roles
      WHERE  rolname = 'ingest') THEN

      CREATE USER ingest WITH ENCRYPTED PASSWORD 'ingest';
   END IF;
END
$$;

GRANT CONNECT ON DATABASE ingest TO ingest;
GRANT USAGE ON SCHEMA public TO ingest;
GRANT INSERT, UPDATE, SELECT ON ALL TABLES IN SCHEMA public TO ingest;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ingest;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT INSERT, UPDATE, SELECT ON TABLES TO ingest;


CREATE TABLE IF NOT EXISTS requests (
  id BIGSERIAL PRIMARY KEY,
  method VARCHAR(20) NOT NULL,
  protocol VARCHAR(20) NOT NULL,
  hostname VARCHAR(2000) NOT NULL,
  url VARCHAR(2000) NOT NULL,
  headers JSONB NOT NULL,
  -- body parser is 100kb
  body VARCHAR(200000) NOT NULL
);

-- down
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL PRIVILEGES ON TABLES FROM ingest;
REVOKE USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public FROM spool;
REVOKE ALL PRIVILEGES ON TABLE knex_migrations, knex_migrations_lock FROM ingest;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM ingest;
REVOKE ALL PRIVILEGES ON DATABASE ingest FROM ingest;
DROP USER IF EXISTS ingest;
